name: capataz-simple-example
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-capataz
extra-source-files:
- README.md
dependencies:
- base >= 4 && < 5
- optparse-generic >= 1.1.1
- pretty-show >= 1.6.13
- typed-process >= 0.1.0
- rio >= 0.1.2.0
- random >= 1.1
library:
  exposed-modules:
  source-dirs: src/lib
  exposed-modules:
  - Lib
executables:
  example1:
    main: Main.hs
    source-dirs: src/example1
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - capataz-simple-example
  example2:
    main: Main.hs
    source-dirs: src/example2
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - capataz
    - capataz-simple-example
