name: capataz
version: '0.2.0.0'
synopsis: OTP-like supervision trees in Haskell
description: |
  `capataz` enhances the reliability of your concurrent applications by offering
  supervision of green threads that run in your application.

  Advantages over standard library:

  * Links related long-living processes together under a common capataz
    supervisor, with restart/shutdown order

  * Set restart strategies (Permanent, Transient, Temporary) on `IO`
    sub-routines on a granular level

  * Set restart strategies on a pool of long-living worker threads (AllForOne,
    OneForOne)

  * Complete telemetry on the sub-routine lifecycle of your application (start,
    error, restarts, shutdown)

category: Control, Concurrency
author: Roman Gonzalez
maintainer: open-source@roman-gonzalez.info
copyright: © 2018 Roman Gonzalez
license: MIT
license-file: LICENSE
github: roman/Haskell-capataz
tested-with: GHC==8.0.1 GHC==8.0.2 GHC==8.2.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates

dependencies:
- base >= 4 && < 5
- async >=2.1.1.1 && <2.3
- bytestring >= 0.10.8
- rio >= 0.1.2.0
- time >= 1.6.0
- teardown >=  0.5.0.0
- uuid >= 1.3
- prettyprinter >= 1.1
- pretty-show >= 1.6.13

library:
  source-dirs: src
  exposed-modules:
  - Capataz
  - Control.Concurrent.Capataz
  - Control.Concurrent.Capataz.Event
  - Control.Concurrent.Capataz.Lens
  - Control.Concurrent.Capataz.Internal.Core
  - Control.Concurrent.Capataz.Internal.Types
  - Control.Concurrent.Capataz.Internal.Types.Lens
  - Control.Concurrent.Capataz.Internal.Supervisor
  - Control.Concurrent.Capataz.Internal.Util
  - Control.Concurrent.Capataz.Internal.Worker

tests:
  capataz-test:
    main: Main.hs
    source-dirs: test/testsuite
    ghc-options:
    - -threaded
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - pretty-show
    - capataz

stability: alpha (experimental)
